branches:
  - "main"
plugins:
  -
    - "@semantic-release/commit-analyzer"
    - preset: "angular"
      releaseRules:
        - type: "feat"
          release: "minor"
        - type: "fix"
          release: "patch"
        - type: "perf"
          release: "patch"
        - type: "revert"
          release: "patch"
        - type: "docs"
          release: "patch"
        - type: "style"
          release: "patch"
        - type: "refactor"
          release: "patch"
        - type: "test"
          release: "patch"
        - type: "chore"
          release: "patch"
        - type: "ci"
          release: "patch"
      parserOpts:
        noteKeywords:
          - "BREAKING CHANGE"
          - "BREAKING CHANGES"
  - 
    - "@semantic-release/release-notes-generator"
    - preset: "angular"
    - 
  - "@semantic-release/github"
  - "@semantic-release/npm"