name: release
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
      id-token: write 
      contents: write
      packages: write
jobs:
  release:
    name: release
    runs-on: self-hosted
    concurrency: 
      group: deploy-${{github.ref}}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://npm.pkg.github.com'
          scope: '@aeroview'
          cache: 'npm'
      - name: Cache project's node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{runner.os}}-node-${{hashFiles('package-lock.json')}}
      - name: Install app dependencies cleanly
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Linting
        run: npm run lint
      - name: Unit tests
        run: npm test
      - name: Build for package
        run: npm run build-package
      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}